### PR TITLE
solutions nb for unet training vertex

### PR DESCRIPTION
**Pull request by kylesteckler**
Environment:
- TF 2.8 
- Notebook with 1 Tesla T4 
- Model will train without GPU but takes ~45 minutes.

### CODE REVIEW

**Comment by kylesteckler** [comment]
<p>Removed for simplicity. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kylesteckler** [comment]
<p>Created local training section and left vertex training as optional section.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kylesteckler** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kylesteckler** [comment]
<p>Done. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
<p>I cannot see explanations yet.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
Added some minor suggestions, but it is now much more handy and clearer!

**Review by takumiohym — APPROVED** [review]
Added some minor suggestions, but it is now much more handy and clearer!

**Comment by kylesteckler** [comment]
<p>Done. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kylesteckler** [comment]
<p>Linked the research paper (that includes images) instead. Thoughts? </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kylesteckler** [comment]
<p>Added explanation in markdown. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kylesteckler** [comment]
<p>Done. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>+1 I'd also add a visual of the architecture. Maybe the diagram on slide 18 of the corresponding deck.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>+1. I'd have the <code>upsample</code> separate in its own code cell with some markdown explaining what it does (including the stride=2). This would also decrease the amount of code in the whole cell.  Also, there are a few non-trivial manipulations in the <code>build_unet</code> function that need explanation (e.g. why do we need <code>down_stack.trainable = False</code>  or what the numbers "512", "256"  mean in the <code>upstack</code> list. For the sake of clarity, consider defining the unet model outside of a function so that each block of code can be defined in its own markdown cell, and separately explained in a markdown cell.  </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>+1</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>I am not sure what these functions are doing. Consider having them in their separate code cells with an explanation of what they do in a markdown cell above. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kylesteckler** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sanjanalreddy** [comment]
<p>nit: can you make the image smaller in size?</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sanjanalreddy** [comment]
<p>I agree with Benoit, I think it would be nicer to break this code block into their own cells.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/227/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by sanjanalreddy — APPROVED** [review]
Just a few minor comments to explain two things better apart from that LGTM

**Review by BenoitDherin — APPROVED** [review]
LGTM.

**Pull request merged**
