### PR TITLE
Update train.py

### PR DESCRIPTION
**Pull request by paulleroyza**
Changed line 56 to log_loss to fix hptune error once deployed

### CODE REVIEW

**Comment by takumiohym** [comment]
@paulleroyza What kind of issue is this trying to resolve?
Also, since there are multiple files using the same module and parameter, all should be updated if there is a common issue.
https://github.com/search?q=repo%3AGoogleCloudPlatform%2Fasl-ml-immersion%20SGDClassifier&type=code

Thanks!

**Comment by paulleroyza** [comment]
Hold off on this for now, it is affecting multiple labs (at least three of
the kfp ones and the basic one), but there is another issue that breaks the
pipeline run which this doesn't solve. I'll work through this an try to
solve both issues.

**Comment by takumiohym** [comment]
@paulleroyza 
Thanks!
I'd appreciate it if you could share the detail of the issue (with error messages if possible).

**Comment by paulleroyza** [comment]
Moved to Pull https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/398, there was an issue with my CLA, I have reverted it back to this user now, but it failed the check.

**Pull request closed without merging**
