### PR TITLE
update text_models notebooks for TF2.12

### PR DESCRIPTION
**Pull request by sanjanalreddy**
A couple of updates to these notebooks
- Updated the BQ queries because the dataset table has been renamed
- Added logging statements to not show unnecessary logs
- Updated imports that are no longer experimental

### CODE REVIEW

**Review by BenoitDherin — APPROVED** [review]
LGTM

**Comment by takumiohym** [comment]
@sanjanalreddy 
Regarding the BERT kernel, could you also remove it from [Makefile](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/dev_module_update_202307/Makefile) and delete [bash file](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/dev_module_update_202307/kernels/bert_kernel.sh)? Thanks!

**Comment by sanjanalreddy** [comment]
@takumiohym Thanks for catching that! I'll remove those references and will send a PR to remove that.

**Comment by sanjanalreddy** [comment]
@takumiohym I just made the changes directly to the `dev_module_update_202307` branch. See [this commit](https://github.com/GoogleCloudPlatform/asl-ml-immersion/commit/bf4f6fb1a83175d77d709850d72f142b14f77450).

**Comment by takumiohym** [comment]
@sanjanalreddy Looks great! Thank you!

**Pull request merged**
