### PR TITLE
added an optional variational autoencoder lab

### PR DESCRIPTION
**Pull request by takumiohym**
Optional Variational Autoencoder lab that follows #211.
I will create a lab exercise version after the review.

### CODE REVIEW

**Review by BenoitDherin — CHANGES_REQUESTED** [review]
This lab has a lot of overlap with the auto-encoder lab for anomaly detection (PR #221). An explanation of how different the use of auto-encoder w.r.t. the lab in #221 is may be useful. Also most of the comments for PR #221 are also valid for this lab:

codewise:
* parametrize model code avoiding hard-coded values for the parameters
* avoid abbreviations in the variable names

More explanations are needed as to what this lab implements and why, as well as a description of what each code cell does.

**Comment by takumiohym** [comment]
Thanks @BenoitDherin !
Yes I agree there are a lot of overlaps with #211 . Do you think it is better just to add an optional Variational Autoencoder section at the end of the autoencoder lab than creating a separate notebook for this?

**Review by sanjanalreddy — APPROVED** [review]
Minor markdown comments. Good to merge after they are addressed!

**Comment by takumiohym** [comment]
<p>Added. Thanks!</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/212/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
<p>Modified. Thanks!</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/212/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
<p>Thank you :)</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/212/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
<p>Added. Thanks!</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/212/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
<p>Thank you! </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/212/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
<p>Thank you.</p><p>I expanded the  explanation on VAE and its advantages here. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/212/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
