### PR TITLE
Vertex AI Image Classifier with Explainable Predictions (solution notebook) 

### PR DESCRIPTION
**Pull request by kylesteckler**
Solution Notebook for XAI Image Lab with Vertex. #165 
- Explore flower dataset
- Build/package tensorflow model to train on Vertex AI
- Train on Vertex AI 
- Upload/deploy model to Vertex AI 
- Serve predictions and visualize feature attributions from IG

### CODE REVIEW

**Comment by sanjanalreddy** [comment]
<p>+1</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/168/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sanjanalreddy** [comment]
<p>Just a brief comment on what the architecture of the model is would be helpful in the markdown above. Since we aren't focusing on model building here, it might be useful to mention what kind of model we are using. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/168/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sanjanalreddy** [comment]
<p>Agree. It's not clear what the purpose is.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/168/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by sanjanalreddy — COMMENTED** [review]
Thanks for updating this. Just added minor suggestions to improve the instructions!

**Review by BenoitDherin — COMMENTED** [review]
Added a few minor comments. Thanks for updating the lab.

**Comment by takumiohym** [comment]
<p>+1</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/168/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
<p>In terms of the model, how about just doing transfer learning?</p><p>That can shorten the training time, and get better result (and better explainability).</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/168/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kylesteckler** [comment]
<p>When I run this one-liner with BUCKET='kylesteckler-demo' I get an error: </p><p> </p><pre class="ql-syntax" spellcheck="false">InvalidUrlError: Invalid bucket name in URL "-demo".
</pre><p> </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/168/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>Have you tried quoting the bucket path as follows:</p><p> </p><p><code></code><code></p><p>!gsutil ls -d | grep -w "gs://${BUCKET}/" || gsutil mb -l ${REGION} "gs://${BUCKET}"</p><p></code><code></code></p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/168/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p><strong>New comment:</strong> Did you run pre-commit? The code still doesn't look fully pep8 compliant (e.g., only one line between functions, lines looking too long) </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/168/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
LGTM. nit: It seems at time the code is not fully pep8 compliant.

**Review by sanjanalreddy — APPROVED** [review]
LGTM

**Review by takumiohym — APPROVED** [review]
LGTM! Thanks for updating this.

**Pull request merged**
