### PR TITLE
Adjust lat and lon buckets

### PR DESCRIPTION
**Pull request by JasonParker**
We noticed these were switched during the lab exercises this week, though I don't think it actually matters to the model.

### CODE REVIEW

**Comment by JasonParker** [comment]
@googlebot I signed it!

**Comment by danielsparing** [comment]
Hi @JasonParker , thank you for contributing!

Could you elaborate on the kind of problem you're trying to solve? In your particular code change, you are linking `longitude` to `latbucket` instead of `lonbucket`, etc, which does seem backwards, as `lonbucket` (and an approximate value of `-73, -74`) should indeed relate to `longitude`, as it is originally.

But maybe there is something else mixed up, that you are attempting to fix?

Maybe your concern is that almost all values in the training data end up in the same one bucket? I do see that as something that could be improved, but then the `linspace` function `start` and `stop` could be adjusted to zoom in on NYC coordinates, such as:

```
latbuckets = np.linspace(start=40.65, stop=40.80, num=NBUCKETS).tolist()
lonbuckets = np.linspace(start=-74.05, stop=-73.85, num=NBUCKETS).tolist()
```

**Comment by JasonParker** [comment]
The current code has these backwards, I was just suggesting switching them so that the names would match up with their contents.

**Comment by danielsparing** [comment]
Ah I see, sorry -- in principle you are right but there are actually three places per line where lat/lon is referenced, not just two :)

Originally, there was: `fc_bucketized_plat`, `pickup_longitude`, and `lonbuckets`. (Note `lat`, `lon`, `lon`)
You are changing them to `fc_bucketized_plat`, `pickup_longitude`, and `latbuckets` (Note `lat`, `lon`, `lat`)
 
Now there's still a mismatch, but instead of between `fc_bucketized_plat` and the rest, now the mismatch is between the `pickup_longitude` and the rest.

So you'd need to either flip also the `pickup_longitude` etc, or revert your change and flip `fc_bucketized_plat` etc isntead.

With that simple change, it would be perfect and I'd be happy to merge!

**Comment by danielsparing** [comment]
thanks again @JasonParker , I made these minor updates as above discussed, and merging.

**Pull request merged**
