### PR TITLE
Uncertainty Aware Models with SNGP

### PR DESCRIPTION
**Pull request by BenoitDherin**
This lab illustrates various approaches to make a model predictions uncertain when confronted with input points far away from the training distribution. It focuses on the Spectral Normalized Gaussian Process (SNGP) approach. 

The lab uses the model API approach rather than the functional API so that an existing model can be tweaked easily by subclassing it and implementing in the derived class the SNGP tweaks. 

**Note:** Test with JupyterLab TF 2.8 (no need of GPU).

### CODE REVIEW

**Comment by sanjanalreddy** [comment]
<p>+1 I think the equation below will really help explain the concepts here better. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/259/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>Done! (I commented the constants, and moved that cell into the "Two moon dataset" section)</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/259/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>Done! </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/259/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>Thanks! Done!</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/259/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sanjanalreddy** [comment]
@BenoitDherin I reviewed the whole notebook and it's a very clear notebook and I don't have any other comments. LGTM!

**Review by sanjanalreddy — APPROVED** [review]
LGTM

**Comment by BenoitDherin** [comment]
<p>Done!</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/259/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by takumiohym — APPROVED** [review]
Added a few minor comment, but LGTM! This is a great addition. Thanks!

**Comment by BenoitDherin** [comment]
<p>Done!</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/259/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<ul><li>pip now works without the magic (like a few other commands)</li><li>I'll add the dep to the requirements.txt but I'll comment it out for now. The reason is that the current requirements are for the MLOps part which needs TF 2.6, and unfortunately <code>tf-models-official==2.8.0</code> will upgrade to TF 2.8, breaking the MLOPs labs. When we upgrade the MLOPs labs to TF 2.8, we will just have to uncomment that dep. </li></ul>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/259/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
@BenoitDherin In terms of  `!` magic, I am seeing this syntax error without it.
`pip` command itself does work, but it seems this concatenated command requires `!` magic. Or am I missing something?

Screen Shot 2022-09-19 at 13 46 04

**Pull request merged**
