### PR TITLE
Update cloudbuild_vertex.yaml

### PR DESCRIPTION
**Pull request by paulleroyza**
Added logging setting, this fixes a break with the new requirement for the service account for cloud build to be set

### CODE REVIEW

**Comment by takumiohym** [comment]
Thanks Paul, could you elaborate a bit more about what the new requirement is and the error you are seeing?
It works fine on my end.

In terms of the service account setup for Cloud Build, it is included in the [scripts/setup_on_cloudshell.sh](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/scripts/setup_on_cloudshell.sh) which should be run in the setup process as described in the README.md.

**Comment by paulleroyza** [comment]
Hey Takumi,

When running the the trigger either manually or by push and a service
account is specified for the build it causes an error on the logging, it
may be that there is some intricacy in the GitHub linking and the new
source repos we missed.

**Comment by takumiohym** [comment]
Could you share the error log? It seems to be working without any errors on my end.
Also, could you make sure you setup the environment following the README.md?

**Comment by takumiohym** [comment]
@paulleroyza Any update on this? If not let us close this PR since we couldn't reproduce the issue.
Thanks!

**Comment by paulleroyza** [comment]
HiTakumi, it seems that this is specific to when the github link is set up,
I'd have to run through this from scratch to see.

Regards,
Paul

**Comment by takumiohym** [comment]
Hi @paulleroyza,

I investigated the recent change in the Cloud Build, and I could reproduce the issue you might have seen.
As you may be aware, the issue is related to the recent Cloud Build service account change, and it happens only in new projects.
https://cloud.google.com/build/docs/cloud-build-service-account-updates

I addressed the issue in #500. Please check the solution when you have time!

Again, thank you for reporting this issue!

**Pull request closed without merging**
