### PR TITLE
pre-commit manual update

### PR DESCRIPTION
**Pull request by takumiohym**
Pre-commit auto-update PR was generated automatically, but it failed at Google CLA check since it is a bot.
https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/232

I tentatively merged the PR to check if there is any issues, and reverted again.
https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/234

I copied the commit and recreated this PR manually. 
There are multiple minor issues due to pre-commit version change. So the files appearing in the error message below need to be updated at the same time.

### CODE REVIEW

**Comment by takumiohym** [comment]
@sanjanalreddy Yeah it is just a warning, but the problem is that the CLA check failure blocked the pre-commit check process on github, so needed to merge and check it manually.

Maybe so far we should prioritize the other PRs? I am happy to update it next week.

**Comment by takumiohym** [comment]
It seems when CLA fails the pre-commit check process is not executedat all. That was happening in #232.
Regarding the testing, you’re completely right. I will deal with this after all the preprocessing layer PRs are merged. Thanks!

**Comment by sanjanalreddy** [comment]
It is executed independent of the CLA check. Here's the pre-commit run from the same PR you have linked #232  Here's the run link: https://results.pre-commit.ci/run/github/271800973/1656967961.cpe8QTlGSgiw5rCgo_gsdg The check failed because of pylint failing not because of CLA check failing.

**Comment by takumiohym** [comment]
Oh thanks! So it was just not appearing on the PR page due to CLA failure, but we can check pre-commit history directly.
I didn’t know this. Thanks!

**Comment by takumiohym** [comment]
As discussed, I modified these 3 things:
- Removed the deprecated options from pylintrc
- Removed the estimator model from TFX guided project lab
- Removed test.py under `mnist_models`

Feel free to merge if it looks good to you.

**Review by sanjanalreddy — APPROVED** [review]
LGTM

**Review by BenoitDherin — COMMENTED** [review]
LGTM. Thanks for taking care of that!

**Pull request merged**
