### PR TITLE
added autoencoder and anomaly detection solution notebook

### PR DESCRIPTION
**Pull request by takumiohym**
New autoencoder and anomaly detection notebook.
I will create a lab exercise version after the review.

### CODE REVIEW

**Review by BenoitDherin — CHANGES_REQUESTED** [review]
Very interesting lab! Great addition! Thanks @takumiohym 

Except minor issues (e.g. variable names and hard-coded constants), the code looks good! The lab itself needs some more explanations of the main concepts though. I tried to point out where to add explanations and what to add.

**Comment by takumiohym** [comment]
<p>Thanks for this comments. Actually Sequential API works in this case, since codes defines encoder and decoder separately at first. So far I modified this part to Sequential, and add an explanation of Functional API in optional Variational Autoencoder lab.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/211/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>* name="encoder_dense" -&gt; name="encoder_output" (this is clearer)</p><p>* Still a lot of hard-coded parameters. If you really want to keep them hard-coded in the model, use the argument names so that it's clear what these numbers correspond to: e.g., "layers.Conv2D(32," -&gt; "layers.Conv2D(filters=32,"</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/211/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>* Same remark as above concerning the hard-coded filters and kernel_size (use the argument names so that we know what these numbers mean)</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/211/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>Great!</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/211/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by BenoitDherin — CHANGES_REQUESTED** [review]
Please have a careful pass at the spelling and syntax. There are a number of places where the explanations given need to be expanded. 

In terms of code, I suggested a strategy to avoid duplicating the model just to change the latent space dimension.

**Comment by takumiohym** [comment]
<p>Thanks. In terms of the forth point, I added in Anomaly Detection section. </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/211/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
<p>Agreed! Thanks.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/211/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by BenoitDherin** [comment]
<p>Great! </p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/211/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by BenoitDherin — APPROVED** [review]
Great lab! I really like the new way you remove the need to parametrize the decoder. Added a few very minor editing suggestions, but otherwise LGTM!

**Comment by takumiohym** [comment]
<p>Thank you! :)</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/211/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
<p>Thank you. It is much clearer!</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/asl-ml-immersion/pull/211/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by takumiohym** [comment]
I appreciate it if you could also check this lab. @sanjanalreddy @kylesteckler 
I will merge with one more LGTM :)

**Review by sanjanalreddy — APPROVED** [review]
LGTM! Great lab, Takumi!

**Comment by takumiohym** [comment]
@sanjanalreddy Thank you!

**Pull request merged**
